### ISSUE TITLE
Duplicate choruses

### ISSUE THREAD

**Issue by iRoachie** [iRoachie/ay-sing#4]
Check through songs 70 + for duplicate choruses. And make sure to put the strong tag around the chorus.

`<strong>Chorus:</strong>`

**Comment by dehjokker** [comment]
on it boss :D

**Comment by iRoachie** [comment]
@dehjokker Lol this joker

**Comment by dehjokker** [comment]
So we only want one iteration of the chorus, and removal of the duplicates
right?

**Comment by iRoachie** [comment]
Yea that's it!

**Comment by iRoachie** [comment]
71-100 covered in Commit: 012317a13831aefc037a77df66f5a1738b829a17
